# Generated by Django 4.1.4 on 2023-01-10 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('title',
                models.CharField(max_length=200, verbose_name='Naming')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter post text',
                    verbose_name='Text')),
                ('pub_date',
                models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('image',
                models.ImageField(blank=True, null=True, upload_to='posts/',
                    verbose_name='Image')),
                ('author',
                models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='posts', to=settings.AUTH_USER_MODEL,
                    verbose_name='Author')),
                ('group', models.ForeignKey(blank=True,
                    help_text='Group, to each post is connected to', null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='posts', to='posts.group',
                    verbose_name='Group')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('author',
                models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user',
                models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text="Enter comment's text",
                    max_length=255, verbose_name="Comment's text")),
                ('created',
                models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('author',
                models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments', to=settings.AUTH_USER_MODEL,
                    verbose_name='Author')),
                ('post',
                models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments', to='posts.post',
                    verbose_name='Post')),
            ],
        ),
    ]
